### PR TITLE
feat: support text color / text color / br rule

### LINKED ISSUE #2: text suggestion
you can adjust the parameters of the text to Text type, in this type you can set the text alignment (center, left, right), text color, and even in a line can be put into the Text multiple times, for example, into the two Text a left, a right.

### PR DESCRIPTION
**Pull request by fangzhengjin**
image

close #2

### CODE REVIEW

**Comment by tmpfs** [comment]
Overall looks good @fangzhengjin , the tests are failing so need to update the fixtures for the test specs.

Also, I think we should put the additional dependency `colored` behind a feature flag (let's call it `color`), it should be straightforward to do, just put the `TextStyle::color` field and `color()` function behind `#[cfg(feature = "color")]`.

Is that ok?

**Comment by fangzhengjin** [comment]
> Overall looks good @fangzhengjin , the tests are failing so need to update the fixtures for the test specs.
> 
> Also, I think we should put the additional dependency `colored` behind a feature flag (let's call it `color`), it should be straightforward to do, just put the `TextStyle::color` field and `color()` function behind `#[cfg(feature = "color")]`.
> 
> Is that ok?

I try to do it, I'm a rust novice. If there is any error in the code, please tell me immediately.

**Comment by tmpfs** [comment]
Code seems fine to me, if you are not familiar with feature flags and/or need some help let me know and I will demonstrate.

**Comment by fangzhengjin** [comment]
@tmpfs plz review

**Comment by tmpfs** [comment]
Looks good @fangzhengjin, one more small change before we merge this please, can we use a more descriptive name than `br()` - I suggest `newline()` and then the enum variant can be `Newline`.

Thanks 🙏

**Comment by fangzhengjin** [comment]
> Looks good @fangzhengjin, one more small change before we merge this please, can we use a more descriptive name than `br()` - I suggest `newline()` and then the enum variant can be `Newline`.
> 
> Thanks 🙏

Or we should adjust it to divider / divider_with_space / divider_with(char) ?

**Comment by tmpfs** [comment]
> > Looks good @fangzhengjin, one more small change before we merge this please, can we use a more descriptive name than `br()` - I suggest `newline()` and then the enum variant can be `Newline`.
> > Thanks 🙏
> 
> Or we should adjust it to divider / divider_with_space / divider_with(char) ?

I think the API works better with `newline()` rather than overloading `divider()` 👍

**Comment by fangzhengjin** [comment]
> > > Looks good @fangzhengjin, one more small change before we merge this please, can we use a more descriptive name than `br()` - I suggest `newline()` and then the enum variant can be `Newline`.
> > > Thanks 🙏
> > 
> > 
> > Or we should adjust it to divider / divider_with_space / divider_with(char) ?
> 
> I think the API works better with `newline()` rather than overloading `divider()` 👍

set `newline()` to be an alias of `divider_with_space()`, so that you can customize placeholders with `divider_with(char)`.

**Comment by fangzhengjin** [comment]
image

image

**Comment by tmpfs** [comment]
@fangzhengjin, yeh that works for me, you happy with it?

Want me to merge and publish a new crate version?

**Comment by fangzhengjin** [comment]
Yes, it can now meet my usage scenario, and a new version can be released.





------------------ Original ------------------
From: muji ***@***.***&gt;
Date: Sat,Jan 27,2024 2:57 PM
To: 472681523 ***@***.***&gt;
Subject: Re: [tmpfs/terminal-banner] feat: support text color / text color /br rule (PR #3)





 
@fangzhengjin, yeh that works for me, you happy with it?
 
Want me to merge and publish a new crate version?

**Comment by tmpfs** [comment]
@fangzhengjin version 0.3.0 is up on crates.io now 👍

**Pull request merged**
